### ISSUE TITLE
Build frontend service docker image with enabled instrumentation

### ISSUE THREAD

**Issue by pavolloffay** [pavolloffay/kubecon-eu-2023-opentelemetry-kubernetes-tutorial#40]
We should build a frontned service with enabled and configured instrumentation. 

The docker image should be available in the tutorial (e.g. as a docker tag) to participants to override it if needed.

**Comment by svrnm** [comment]
this is how I control it right now:

https://github.com/pavolloffay/kubecon-eu-2023-opentelemetry-kubernetes-tutorial/blob/main/app/k8s.yaml#L97

It's just a flag that makes use of the instrumentation.

But I can create 2 independent docker images as well (one that has that env set to true and one that has set it to false)
