### ISSUE TITLE
Manually instrument one service

### ISSUE THREAD

**Issue by pavolloffay** [pavolloffay/kubecon-eu-2023-opentelemetry-kubernetes-tutorial#5]
One service should be manually/explicitly instrumented with OTEL API and SDK. 

I would like to include the instrumentation code as comments in the service codebase (as opposed of using git branches).

The instrumentation code can as well show how to add additional tags via annotations or other language constructs that simplify interaction with OTEL API.

**Comment by svrnm** [comment]
done
